In [1]:
import pandas as pd
import sqlite3

In [2]:
conn=sqlite3.connect('inventory.db')

In [3]:
tables=pd.read_sql_query("select name from sqlite_master where type='table'",conn)
tables

                   name
0       begin_inventory
1         end_inventory
2             purchases
3       purchase_prices
4                 sales
5        vendor_invoice
6  vendor_sales_summary

In [4]:
pd.read_sql("select count(*) from purchases",conn)

# # Option 2: squeeze to Series → int
# count = pd.read_sql("select count(*) from purchases", conn).squeeze()
# print(count)

   count(*)
0   2372474

In [5]:
for table in tables['name']:
    print('<---',f'{table}','--->')
    print('Count of records:', pd.read_sql(f"select count(*) as count from {table}",conn)['count'].values[0])
    display(pd.read_sql(f"select * from {table} limit 5", conn))

<--- begin_inventory --->
Count of records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.990000,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.990000,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.990002,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.990002,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.990002,2024-01-01

<--- end_inventory --->
Count of records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.990000,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.990002,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.990002,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.990002,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.990000,2024-12-31

<--- purchases --->
Count of records: 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.709999,6,214.259995,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.350000,4,37.400002,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.410000,5,47.049999,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.350000,6,56.099998,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.320000,5,106.599998,1

<--- purchase_prices --->
Count of records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.990000,750mL,750,1,9.280000,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.990002,750mL,750,1,28.670000,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.990002,750mL,750,1,30.459999,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.990002,750mL,750,1,26.110001,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.990000,750mL,750,1,10.940000,7245,PROXIMO SPIRITS INC.

<--- sales --->
Count of records: 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.490000,16.490000,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.980000,16.490000,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.490000,16.490000,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.490000,14.490000,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.980003,34.990002,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

<--- vendor_invoice --->
Count of records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.470000,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.570000,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.610000,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.199951,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.200012,None

<--- vendor_sales_summary --->
Count of records: 10692

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.270000,36.990002,1750.0,145080,3.811252e+06,142049.0,5.101920e+06,672819.341167,260999.198781,68601.680141,1.290668e+06,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.190001,28.990000,1750.0,164038,3.804041e+06,160247.0,4.819073e+06,561512.375851,294438.657920,144929.240166,1.015032e+06,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.240000,24.990000,1750.0,187407,3.418304e+06,187140.0,4.538121e+06,461140.145689,343854.067793,123780.220203,1.119817e+06,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.170000,22.990000,1750.0,201682,3.261198e+06,200412.0,4.475973e+06,420050.005789,368242.797294,257032.069523,1.214775e+06,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.889999,29.990000,1750.0,138109,3.023206e+06,135838.0,4.223108e+06,545778.283312,249587.828808,257032.069523,1.199902e+06,28.412765,0.983556,1.396897

##### As the data that we need for analysis is distributed in different tables, we need to create a summary table containing:
##### purchase transactions made by vendors, sales transaction data, freight costs for each vendorm actual product prices from vendors

In [6]:
freight_summary = pd.read_sql_query("""select VendorNumber, sum(Freight) as FreightCost from vendor_invoice
group by VendorNumber""",conn)
freight_summary

     VendorNumber  FreightCost
0               2    27.080001
1              54     0.480000
2              60   367.520002
3             105    62.389999
4             200     6.190000
..            ...          ...
121         98450   856.019997
122         99166   130.090001
123        172662   178.340000
124        173357   202.500001
125        201359     0.090000

[126 rows x 2 columns]

In [7]:
purchas=pd.read_sql_query("""select p.VendorNumber, p.VendorName, p.Brand, p.PurchasePrice,pp.volume,pp.Price as ActualPrice,
sum(p.Quantity) as TotalPurchaseQuantity,
sum(p.Dollars) as TotalPurchaseDollars
from purchases p join purchase_prices pp on p.Brand=pp.Brand
where p.PurchasePrice > 0
group by p.VendorNumber, p.VendorName, p.Brand
order by TotalPurchaseDollars""",conn)

purchas

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,7245,PROXIMO SPIRITS INC.,3065,0.710000,50,0.990000,1,7.100000e-01
1,3960,DIAGEO NORTH AMERICA INC,6127,1.470000,200,1.990000,1,1.470000e+00
2,3924,HEAVEN HILL DISTILLERIES,9123,0.740000,50,0.990000,2,1.480000e+00
3,8004,SAZERAC CO INC,5683,0.390000,50,0.490000,6,2.340000e+00
4,9815,WINE GROUP INC,8527,1.320000,750,4.990000,2,2.640000e+00
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.889999,1750,29.990000,138109,3.023206e+06
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.170000,1750,22.990000,201682,3.261198e+06
10689,17035,PERNOD RICARD USA,8068,18.240000,1750,24.990000,187407,3.418304e+06
10690,4425,MARTIGNETTI COMPANIES,3405,23.190001,1750,28.990000,164038,3.804041e+06
10691,1128,BROWN-FORMAN CORP,1233,26.270000,1750,36.990002,145080,3.811252e+06

In [8]:
sale=pd.read_sql_query("""select VendorNo, Brand, sum(SalesDollars) as TotalSalesDollars,
sum(SalesPrice) as TotalSalesPrice, sum(SalesQuantity) as TotalSalesQuantity, sum(ExciseTax) as
TotalExciseTax from sales
group by VendorNo, Brand order by TotalSalesDollars""",conn)

sale

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,8004,5287,9.800000e-01,0.980000,2,0.100000
1,9206,2773,9.900000e-01,0.990000,1,0.050000
2,3252,3933,1.980000e+00,0.990000,2,0.100000
3,3924,9123,1.980000e+00,0.990000,2,0.100000
4,10050,3623,1.980000e+00,1.980000,2,0.100000
...,...,...,...,...,...,...
11267,3960,3545,4.223108e+06,545778.283312,135838,249587.828808
11268,3960,4261,4.475973e+06,420050.005789,200412,368242.797294
11269,17035,8068,4.538121e+06,461140.145689,187140,343854.067793
11270,4425,3405,4.819073e+06,561512.375851,160247,294438.657920
11271,1128,1233,5.101920e+06,672819.341167,142049,260999.198781

In [9]:
# import time

# start=time.time()
# final_tb=pd.read_sql_query("""select 
# pp.VendorNumber, pp.Brand, pp.Price as ActualPrice, pp.PurchasePrice,
# sum(s.SalesQuantity) as TotalSalesQuantity, sum(s.SalesDollars) as TotalSalesDollars,
# sum(s.SalesPrice) as TotalSalesPrice, sum(s.ExciseTax) as TotalExciseTax, 
# sum(vi.Quantity) as TotalPurchaseQuantity,
# sum(vi.Dollars) as TotalPurchaseDollars,
# sum(vi.Freight) as TotalFreightCost
# from purchase_prices pp
# join sales s on pp.VendorNumber = s.VendorNo and pp.Brand = s.Brand
# join vendor_invoice vi on pp.VendorNumber = vi.VendorNumber
# group by pp.VendorNumber, pp.Brand, pp.Price, pp.PurchasePrice""",conn)

# end=time.time()

# # time consuming need to optimize query

In [10]:
vendor_sales_summary = pd.read_sql_query("""
WITH
FreightSummary AS (
    SELECT VendorNumber, SUM(Freight) AS FreightCost 
    FROM vendor_invoice
    GROUP BY VendorNumber
),

PurchaseSummary AS (
    SELECT p.VendorNumber, p.VendorName, p.Brand, p.Description, p.PurchasePrice,
           pp.volume, pp.Price AS ActualPrice, 
           SUM(p.Quantity) AS TotalPurchaseQuantity,
           SUM(p.Dollars) AS TotalPurchaseDollars
    FROM purchases p 
    JOIN purchase_prices pp ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY p.VendorNumber, p.VendorName, p.Brand, p.Description, p.PurchasePrice,
             pp.volume, pp.Price
    ORDER BY TotalPurchaseDollars
),

SalesSummary AS (
    SELECT VendorNo, Brand, 
           SUM(SalesDollars) AS TotalSalesDollars,
           SUM(SalesPrice) AS TotalSalesPrice, 
           SUM(SalesQuantity) AS TotalSalesQuantity, 
           SUM(ExciseTax) AS TotalExciseTax 
    FROM sales
    GROUP BY VendorNo, Brand
)

SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ss.TotalSalesQuantity,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.TotalExciseTax,
    fs.FreightCost
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss 
       ON ps.VendorNumber = ss.VendorNo 
      AND ps.Brand = ss.Brand
LEFT JOIN FreightSummary fs 
       ON ps.VendorNumber = fs.VendorNumber
ORDER BY ps.TotalPurchaseDollars DESC
""", conn)

In [11]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.270000,36.990002,1750,145080,3.811252e+06,142049.0,5.101920e+06,672819.341167,260999.198781,68601.680141
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.190001,28.990000,1750,164038,3.804041e+06,160247.0,4.819073e+06,561512.375851,294438.657920,144929.240166
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.240000,24.990000,1750,187407,3.418304e+06,187140.0,4.538121e+06,461140.145689,343854.067793,123780.220203
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.170000,22.990000,1750,201682,3.261198e+06,200412.0,4.475973e+06,420050.005789,368242.797294,257032.069523
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.889999,29.990000,1750,138109,3.023206e+06,135838.0,4.223108e+06,545778.283312,249587.828808,257032.069523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.320000,4.990000,750,2,2.640000e+00,5.0,1.595000e+01,10.960000,0.550000,27100.410036
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.390000,0.490000,50,6,2.340000e+00,134.0,6.566000e+01,1.470000,7.040000,50293.619843
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.740000,0.990000,50,2,1.480000e+00,2.0,1.980000e+00,0.990000,0.100000,14069.870026
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.470000,1.990000,200,1,1.470000e+00,72.0,1.432800e+02,77.610000,15.120000,257032.069523
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.710000,0.990000,50,1,7.100000e-01,86.0,8.514000e+01,33.660000,4.460000,38994.780066

In [12]:
# Export DataFrame to CSV
vendor_sales_summary.to_csv("vendor_sales_summary.csv", index=False)

#### This query generates a vendor-wise sales and purchase summary, which is valuable for:
#### Performance Optimization:
- The query involves heavy joins and aggregations on large datasets like sales and purchases.
 - Storing the pre-aggregated results avoids repeated expensive computations.
 - Helps in analyzing sales, purchases, and pricing for different vendors anti brands.
 - Future Benefits of Storing this data for faster Dashboarding & Reporting.
 - Instead of running expensive queries each time, dashboards can fetch data quickly from vendor_sales_summary.

In [13]:
vendor_sales_summary["TotalPurchaseDollars"]

0        3.811252e+06
1        3.804041e+06
2        3.418304e+06
3        3.261198e+06
4        3.023206e+06
             ...
10687    2.640000e+00
10688    2.340000e+00
10689    1.480000e+00
10690    1.470000e+00
10691    7.100000e-01
Name: TotalPurchaseDollars, Length: 10692, dtype: float64

In [14]:
pd.set_option("display.float_format", "{:.2f}".format)

In [15]:
vendor_sales_summary["TotalPurchaseDollars"]

0       3811251.60
1       3804041.22
2       3418303.68
3       3261197.94
4       3023206.00
           ...
10687         2.64
10688         2.34
10689         1.48
10690         1.47
10691         0.71
Name: TotalPurchaseDollars, Length: 10692, dtype: float64

In [16]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
PurchasePrice            float64
ActualPrice              float64
volume                    object
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [17]:
vendor_sales_summary.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
Description                0
PurchasePrice              0
ActualPrice                0
volume                     0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
TotalSalesQuantity       178
TotalSalesDollars        178
TotalSalesPrice          178
TotalExciseTax           178
FreightCost                0
dtype: int64

In [18]:
vendor_sales_summary['volume'] = vendor_sales_summary['volume'].astype('float64')

In [19]:
vendor_sales_summary.fillna(0, inplace=True)

In [20]:
vendor_sales_summary['VendorName'] = vendor_sales_summary['VendorName'].str.strip()

In [21]:
vendor_sales_summary['VendorName'].unique()

array(['BROWN-FORMAN CORP', 'MARTIGNETTI COMPANIES', 'PERNOD RICARD USA',
       'DIAGEO NORTH AMERICA INC', 'BACARDI USA INC',
       'JIM BEAM BRANDS COMPANY', 'MAJESTIC FINE WINES',
       'ULTRA BEVERAGE COMPANY LLP', 'STOLI GROUP,(USA) LLC',
       'PROXIMO SPIRITS INC.', 'MOET HENNESSY USA INC', 'CAMPARI AMERICA',
       'SAZERAC CO INC', 'CONSTELLATION BRANDS INC', 'M S WALKER INC',
       'SAZERAC NORTH AMERICA INC.', 'PALM BAY INTERNATIONAL INC',
       'REMY COINTREAU USA INC', 'SIDNEY FRANK IMPORTING CO',
       'E & J GALLO WINERY', 'WILLIAM GRANT & SONS INC',
       'HEAVEN HILL DISTILLERIES', 'DISARONNO INTERNATIONAL LLC',
       'EDRINGTON AMERICAS', 'CASTLE BRANDS CORP.',
       'SOUTHERN WINE & SPIRITS NE', 'STE MICHELLE WINE ESTATES',
       'TRINCHERO FAMILY ESTATES', 'MHW LTD', 'WINE GROUP INC',
       'PERFECTA WINES', 'LUXCO INC', 'TREASURY WINE ESTATES',
       'DIAGEO CHATEAU ESTATE WINES', 'SHAW ROSS INT L IMP LTD',
       'PINE STATE TRADING CO', 'PHILLIPS PRODUCTS CO.',
       'CALEDONIA SPIRITS INC', 'STATE WINE & SPIRITS',
       'KOBRAND CORPORATION', 'BANFI PRODUCTS CORP',
       'VINEYARD BRANDS INC', 'DELICATO VINEYARDS INC',
       'FABRIZIA SPIRITS LLC', 'DUGGANS DISTILLED PRODUCTS',
       'Serralles Usa LLC', 'SEA HAGG DISTILLERY LLC',
       'OLE SMOKY DISTILLERY LLC', 'VRANKEN AMERICA', 'KLIN SPIRITS LLC',
       'LAIRD & CO', 'ADAMBA IMPORTS INTL INC',
       'LATITUDE BEVERAGE COMPANY', 'FREDERICK WILDMAN & SONS',
       'MCCORMICK DISTILLING CO', 'CHARLES JACQUIN ET CIE INC',
       'WESTERN SPIRITS BEVERAGE CO', 'MARSALLE COMPANY',
       'AMERICAN VINTAGE BEVERAGE', 'MANGO BOTTLING INC',
       'SWEET BABY VINEYARD', 'NICHE W & S', 'LABELLE VYDS AND WINERY',
       'FLAG HILL WINERY & VINEYARD', 'SMOKY QUARTZ DISTILLERY LLC',
       'PREMIUM PORT WINES, INC.', 'Russian Standard Vodka',
       'Dunn Wine Brokers', 'WEIN BAUER INC', 'BULLY BOY DISTILLERS',
       'ATLANTIC IMPORTING COMPANY', 'PREMIER DISTRIBUTORS',
       'VINILANDIA USA', 'PARK STREET IMPORTS LLC', 'TAKARA SAKE USA INC',
       'SEA BREEZE CELLARS LLC', 'STARK BREWING COMPANY', 'TY KU LLC',
       'PSP WINES', 'TAMWORTH DISTILLING', 'ZORVINO VINEYARDS',
       'SOUTHERN GLAZERS W&S OF NE', 'HOOD RIVER DISTILLERS, Inc.',
       'CRUSH WINES', 'POVERTY LANE ORCHARDS', 'DJINN SPIRITS LLC',
       'MOONLIGHT MEADERY', 'TALL SHIP DISTILLERY LLC',
       'FORTUNE WINE BROKERS LLC', 'BLACK COVE BEVERAGES', 'VINEXTRA INC',
       'SURVILLE ENTERPRISES CORP', 'JEWELL TOWNE VINEYARDS',
       'SWEETWATER FARM', 'ALTAMAR BRANDS LLC', 'CANDIA VINEYARDS',
       'INCREDIBREW INC', 'ALISA CARR BEVERAGES',
       'STELLAR IMPORTING CO LLC', 'FULCHINO VINEYARD INC',
       'IRA GOLDMAN AND WILLIAMS, LLP', 'Circa Wines',
       'VINEDREA WINES LLC', 'BLACK PRINCE DISTILLERY INC',
       'VINEYARD BRANDS LLC', 'THE IMPORTED GRAPE LLC',
       'WALPOLE MTN VIEW WINERY', 'GILMANTON WINERY & VINEYARD',
       'HAUNTING WHISPER VYDS', 'STAR INDUSTRIES INC.',
       'LOYAL DOG WINERY', 'R.P.IMPORTS INC', 'THE PIERPONT GROUP LLC',
       'APPOLO VINEYARDS LLC', 'BLACK ROCK SPIRITS LLC',
       'CENTEUR IMPORTS LLC', 'HIGHLAND WINE MERCHANTS LLC',
       'AMERICAN SPIRITS EXCHANGE', 'UNCORKED', 'BRONCO WINE COMPANY',
       'MILTONS DISTRIBUTING CO', 'TRUETT HURST', 'LAUREATE IMPORTS CO',
       'FANTASY FINE WINES CORP', 'AAPER ALCOHOL & CHEMICAL CO',
       'SILVER MOUNTAIN CIDERS', 'CAPSTONE INTERNATIONAL',
       'FLAVOR ESSENCE INC'], dtype=object)

In [22]:
vendor_sales_summary['GrossProfit'] = vendor_sales_summary['TotalSalesDollars']-vendor_sales_summary['TotalPurchaseDollars']

In [23]:
vendor_sales_summary['ProfitMargin']=(vendor_sales_summary['GrossProfit'] / vendor_sales_summary['TotalSalesDollars']) *100

In [24]:
vendor_sales_summary['StockTurnover'] = vendor_sales_summary['TotalSalesQuantity'] / vendor_sales_summary['TotalPurchaseQuantity']

In [25]:
vendor_sales_summary['SalestoPurchaseRatio'] = vendor_sales_summary['TotalSalesDollars'] / vendor_sales_summary['TotalPurchaseDollars']

In [26]:
cursor=conn.cursor()

In [27]:
cursor.execute("""CREATE TABLE vendor_sales_summary (
    VendorNumber INT,
    VendorName VARCHAR(100),
    Brand VARCHAR(100),
    Description VARCHAR(100),
    PurchasePrice DECIMAL(10,2),
    ActualPrice DECIMAL(10,2),
    Volume INT,
    TotalPurchaseQuantity INT,
    TotalPurchaseDollars DECIMAL(15,2),
    TotalSalesQuantity INT,
    TotalSalesDollars DECIMAL(15,2),
    TotalSalesPrice DECIMAL(15,2),
    TotalExciseTax DECIMAL(15,2),
    FreightCost DECIMAL(15,2),
    GrossProfit DECIMAL(15,2),
    ProfitMargin DECIMAL(15,2),
    StockTurnover DECIMAL(15,2),
    SalesToPurchaseRatio DECIMAL(15,2),
    PRIMARY KEY (VendorNumber, Brand)
);
""")

OperationalError: table vendor_sales_summary already exists

In [ ]:
pd.read_sql_query("select * from vendor_sales_summary",conn)

In [ ]:
vendor_sales_summary.to_sql('vendor_sales_summary', conn, if_exists = 'replace', index=False)